@startuml

/' diagram meta data start
config=CallConfiguration;
{
  "rootMethod": "org.apache.flink.connector.kafka.source.reader.deserializer.KafkaValueOnlyDeserializationSchemaWrapper#open(InitializationContext)",
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": true,
    "cutInterfaceStructures": true,
    "cutDataStructures": true,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 3,
    "backwardDepth": 3,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showMethodParametersTypes": false,
    "showMethodParametersNames": false,
    "showMethodReturnType": false,
    "showPackageLevels": 2,
    "showCallOrder": false,
    "edgeMode": "MethodsOnly", // TypesOnly, MethodsOnly, TypesAndMethods, MethodsAndDirectTypeUsage
    "showDetailedClassStructure": false
  },
  "rootClass": "org.apache.flink.connector.kafka.source.reader.deserializer.KafkaValueOnlyDeserializationSchemaWrapper",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="LR"
    splines=polyline
    

'nodes 
subgraph cluster_1411517106 { 
   	label=apache
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_1531395264 { 
   	label=flink
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   subgraph cluster_107915419 { 
   	label=KafkaSource
	labeljust=l
	fillcolor=white
	style=filled
   
   KafkaSource958062280XXXcreateReader1173588239[
	label="+ createReader()"
	style=filled
	fillcolor=white
	tooltip="KafkaSource

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_1197422553 { 
   	label=DynamicKafkaSourceReader
	labeljust=l
	fillcolor=white
	style=filled
   
   DynamicKafkaSourceReader2024983610XXXaddSplits917037444[
	label="+ addSplits()"
	style=filled
	fillcolor=white
	tooltip="DynamicKafkaSourceReader

null"
	fontcolor=darkgreen
];

DynamicKafkaSourceReader2024983610XXXhandleSourceEvents1559272223[
	label="+ handleSourceEvents()"
	style=filled
	fillcolor=white
	tooltip="DynamicKafkaSourceReader

&#10;  Duplicate source events are handled with idempotency. No metadata change means we simply skip&#10;  the restart logic.&#10; "
	fontcolor=darkgreen
];
} 

subgraph cluster_1878460784 { 
   	label=KafkaValueOnlyDeserializationSchemaWrapper
	labeljust=l
	fillcolor=white
	style=filled
   
   KafkaValueOnlyDeserializationSchemaWrapper338963448XXXopen1836888271[
	label="+ open()"
	style=filled
	fillcolor=white
	tooltip="KafkaValueOnlyDeserializationSchemaWrapper

&#10;  Initialization method for the schema. It is called before the actual working methods {@link&#10;  #deserialize} and thus suitable for one time setup work.&#10; &#10;  \<p\>The provided {@link DeserializationSchema.InitializationContext} can be used to access&#10;  additional features such as e.g. registering user metrics.&#10; &#10;  @param context Contextual information that can be used during initialization.&#10; "
	penwidth=4
	fontcolor=darkgreen
];
} 
} 
} 

'edges    
DynamicKafkaSourceReader2024983610XXXaddSplits917037444 -> KafkaValueOnlyDeserializationSchemaWrapper338963448XXXopen1836888271;
DynamicKafkaSourceReader2024983610XXXhandleSourceEvents1559272223 -> DynamicKafkaSourceReader2024983610XXXaddSplits917037444;
DynamicKafkaSourceReader2024983610XXXhandleSourceEvents1559272223 -> KafkaValueOnlyDeserializationSchemaWrapper338963448XXXopen1836888271;
KafkaSource958062280XXXcreateReader1173588239 -> KafkaValueOnlyDeserializationSchemaWrapper338963448XXXopen1836888271;
    
}
@enduml