@startuml

/' diagram meta data start
config=CallConfiguration;
{
  "rootMethod": "org.apache.flink.connector.kafka.source.reader.deserializer.KafkaValueOnlyDeserializationSchemaWrapper#deserialize(ConsumerRecord\u003cbyte[], byte[]\u003e,Collector\u003cT\u003e)",
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": true,
    "cutInterfaceStructures": true,
    "cutDataStructures": true,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 3,
    "backwardDepth": 3,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showMethodParametersTypes": false,
    "showMethodParametersNames": false,
    "showMethodReturnType": false,
    "showPackageLevels": 2,
    "showCallOrder": false,
    "edgeMode": "MethodsOnly", // TypesOnly, MethodsOnly, TypesAndMethods, MethodsAndDirectTypeUsage
    "showDetailedClassStructure": false
  },
  "rootClass": "org.apache.flink.connector.kafka.source.reader.deserializer.KafkaValueOnlyDeserializationSchemaWrapper",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="LR"
    splines=polyline
    

'nodes 
subgraph cluster_1411517106 { 
   	label=apache
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_1531395264 { 
   	label=flink
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   subgraph cluster_1878460784 { 
   	label=KafkaValueOnlyDeserializationSchemaWrapper
	labeljust=l
	fillcolor=white
	style=filled
   
   KafkaValueOnlyDeserializationSchemaWrapper338963448XXXdeserialize1004595214[
	label="+ deserialize()"
	style=filled
	fillcolor=white
	tooltip="KafkaValueOnlyDeserializationSchemaWrapper

&#10;  Deserializes the byte message.&#10; &#10;  \<p\>Can output multiple records through the {@link Collector}. Note that number and size of&#10;  the produced records should be relatively small. Depending on the source implementation&#10;  records can be buffered in memory or collecting records might delay emitting checkpoint&#10;  barrier.&#10; &#10;  @param record The ConsumerRecord to deserialize.&#10;  @param out The collector to put the resulting messages.&#10; "
	penwidth=4
	fontcolor=darkgreen
];
} 

subgraph cluster_763542564 { 
   	label=KafkaRecordEmitter
	labeljust=l
	fillcolor=white
	style=filled
   
   KafkaRecordEmitter333549911XXXemitRecord513217180[
	label="+ emitRecord()"
	style=filled
	fillcolor=white
	tooltip="KafkaRecordEmitter

null"
	fontcolor=darkgreen
];
} 
} 
} 

'edges    
KafkaRecordEmitter333549911XXXemitRecord513217180 -> KafkaValueOnlyDeserializationSchemaWrapper338963448XXXdeserialize1004595214;
    
}
@enduml